# Generated by Django 2.2.2 on 2019-06-09 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slots', '0002_auto_20190607_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='parking_mode',
            field=models.CharField(choices=[('hour', 'Hour'), ('day', 'Day')], default='day', help_text='Decides if slot is available by day or hour', max_length=11),
        ),
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('booked', 'booked')], default='available', help_text='Decides if slot is availaible or booked', max_length=11),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('payment_status', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card')], default='Credit Card', max_length=11)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='slots.Slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='ReservedSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slots.Reservation')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slots.Slot')),
            ],
            options={
                'unique_together': {('slot', 'reservation')},
            },
        ),
    ]
