# Generated by Django 2.2.2 on 2019-06-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0003_auto_20190609_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
